name: 'Set dynamically below in a task'

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - ReadMe.md
    - docs/*

variables:
  version.MajorMinor: '1.0' # Manually adjust the version number as needed for semantic versioning. Patch is auto-incremented.
  version.Patch: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(version.Patch)'

pool:
  vmImage: windows-latest # The AzureFileCopy task requires Windows.

steps:
- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
      [string] $buildName = "$(versionNumber)_$(Build.SourceBranchName)"
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.updatebuildnumber]$buildName"

- checkout: self
  clean: true

- task: PowerShell@2
  displayName: Run build script
  inputs:
    targetType: 'inline'
    script: |
      & './build/BuildWebsite.ps1' -WebsiteRootDirectoryPath './src' -OutputDirectoryPath './_WebsiteBuildOutput'

- task: PublishBuildArtifacts@1
  displayName: Publish website build artifact
  inputs:
    PathtoPublish: './_WebsiteBuildOutput'
    ArtifactName: 'WebsiteBuildOutput'
    publishLocation: 'Container'

- task: AzureFileCopy@6
  displayName: Deploy website to Azure
  inputs:
    SourcePath: './_WebsiteBuildOutput'
    azureSubscription: 'DansKingdomWebsite'
    Destination: 'AzureBlob'
    storage: 'danskingdomwebsite'
    ContainerName: '$web'
    CleanTargetBeforeCopy: true
